language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
- docker-compose up -d
script:
- "./build.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: eEp+7gGXifXrOVNktyEcnkDGA8qxmzFNEaKSBBweHOlt8Ce92OfinKHOwcTNRGvbey2eVKmljq8K7VDePgD85sMjincGV97HG4DzPEPZ9Ao2dU9GlBIRr1Zhxf/BzCJ7yjsr53iSAIGryu1JBdjlhP/c9ukEA5kTzQ7SfCa2rO0xyDunA+aIB76LYNxNP7bB33E+D0OoXvAKTk9IjafB51qTEYYWQHpgtZAbNrVx/DoQRJYXDRxaFVjl6Kwm1zPSVw4Ysjf6Lcqo75HxJZT9NHwljfuUZq7HdBy8Y3UcpGogCRnWzyI4fmsePvBLnbErJYqm5ErdDEy+G6wl/cfpvAbFI0MF+lZteNKTmE4yzvbT9vqD/P42kAp5Jfz10O/u0pVMihBiEDJXEr4qecnFQGRvT0R1mlHN9M+6iMH0woEk6L+H+6IaGaNnb0cVPfkxfZGSF+dfBv8H2/VGNfDKwT+3eIj0w1VOgH5wDvI3qG6BrHj1FpTWuCp3e+2zPl+QxDJBhGVpREaJ/YPB/H2SNh4MYG/gVM6dRYgvDJq0knWkHL9XXVsFM0/E/Q2s2bePN/wTKzJrAd+LKwsmOAxp5CQAurbLpftUcvMEMOiPcH9Lm/BGgh2+S4BMd23+nA15VQf786tx+6sL6ttS2wc5GR+byIeZapk5cVVrZ6au8PM=
  - secure: lP11SSJYTwiBt9hlnVuvT6KImkbyTFTrsZjthlPVlYdNCKAq54Y1/6T0RGq7Xn+fHfRjCrtPPjp82w0g5RfjnSkON9EGqBbLaV1O45T6UTBJwDP5QHZz40Z3/krLTu4opVZSTF9CCfNVPKPjDD07ZKCwYl7EeV770BUtnxhEDPTY+O1X2tDIZDtb9TM45bgZvle0zmWRGRt5vXyYnxDaYPdK/8CVV1YyXlv5uoL1u37A93c4FXtC/fGWv10977Abfe6/GaH71Kf1nByxus8gd9wvfgkwsm5qIpFoLp284RUbJfdUzUpcDbBIAkM0xYMAKyr4np9lWc74L6tyvXsLk8v6Lv2T3NQtu5jLxK0Lb0GH2REI5DuBhyZJ/2p5N2FySvjGNDm1ehdliiFTnzvxNx9+5YfbXKWeP7EPlxG9dHFnRQiMIiueIEDEDIuHXYe2f+/7z6y/ucPKJ7hCcA5CCAQrLO0NYl/sZ0Rze81APCae3o25SjU5ntfyf+glFUc6nKYT9D7Tyf/EvtvqyRYeGWUw5IFdUFddYCgiB352Us3wodDFFg1HbYHN5am3XwC3tzjH33+vNNSiSCU1nUdxi/TMhjR4a+a/LsSQEBqFI351e5Bug9iWm5qOWHBDBKbU3BszfETMVJD5Sh3SHVeRAE+jA9oQ5RqYXcR5l2huYao=
